### ISSUE TITLE
Confirm where / how we're hosting

### ISSUE THREAD

**Issue by tommerty** [doras-to/doras#28]
So with the discussion about moving away from Docker, we have to come up with some solutions seeing as we can't get docker working. Here's a list we can go through:

- Self Hosted
  - PM2
  - Caprover/Portainer (will need to fix middleware issue)

- Serverless 
  - Vercel (will cost about 20/40$/m)
  - Netlify (about the same)
  - Clouflare (we tried and failed this one but when it worked it was great, just need no middleware and some sort of error system)
  - Google Cloud (uses docker so we'd run into the same problems)

My take: 
1. We try test out PM2 again and see if we can set up some CICD integration
2. Beg for help in Astro to get Docker working without middleware
If needs be, we can also look into Vercel. If we do make such a move, I've be voting to remove some VPS' to offset the cost however. Vercel does have some cool CI/CD things in place that we could use. With a push to Vercel as well we'd really need to get Doras Pro up and running too to start offsetting costs.

In my opinion, we need to figure this out before launch and not deal with any hefty migrations while launch. I understand about closed alpha, but defo before beta

**Comment by tommerty** [comment]
Testing vercel seems cool, managed to get the docs working: https://doras-docs.vercel.app/

**Comment by trent-gezel** [comment]
dont like pm2

**Comment by tommerty** [comment]
Our options are then currently serverless if we can't get docker to work without middleware.

I've just paid for Paid Cloudflare workers and deployed the `new-frontend-server` branch with success: https://74c8dc3d.doras-landing.pages.dev/

Details here: https://dash.cloudflare.com/772ac0c1796319ad18c4f83e8ab7e80e/pages/view/doras-landing/74c8dc3d-91d2-46d0-a4c5-62286207da74/files

So I guess we need to decide is CF better for the price compared to Vercel

**Comment by tommerty** [comment]
Appears Cloudflare can do what we want at least for now, closing this. Thank you for all the help @trent-gezel ✨
