### ISSUE TITLE
[SUG] - Sitemap

### ISSUE THREAD

**Issue by tommerty** [doras-to/doras#33]
## Please keep `[SUG]` in the title, but replace `title_goes_here` with your title.

**Is your feature request related to a problem? Please describe.**
We need to integrate a sitemap to help with SEO

**Describe the solution you'd like**
Astro sitemap doesn't work due to the `[user].astro` file, so we'll need to work on a way to build and generate our own. We have have it build on deployment and doesn't need to be constantly updated.

**Comment by trent-001** [comment]
sort of done

**Comment by tommerty** [comment]
fixed
