### ISSUE TITLE
[BUG] - Font changing when changing the template

### ISSUE THREAD

**Issue by lady-d-22** [doras-to/doras#35]
## Please keep `[BUG]` in the issue title, and replace `issue_title_here` with your title.

**Describe the bug**
When changing the template on the design page, the font is changing while still show the pre-selected font.

**To Reproduce**
How did you produce this error?

1. Select a font (eg Poppins)
2. Change the template
3. You'll see that the font has changed in the preview screen but the font that was selected (eg Poppins) is still displaying.

**Expected behavior**
The font shouldn't change

**Screenshots**

![image](https://github.com/doras-to/doras/assets/120519321/0c224207-0a5b-44c0-82f6-b5b2566dbe94)

**Desktop (please complete the following information):**

Windows, Chrome 118

**Additional context**

**Comment by trent-gezel** [comment]
Issue has been resolved

https://github.com/doras-to/admin/pull/54
