### ISSUE TITLE
Badge toolip shifting

### ISSUE THREAD

**Issue by tommerty** [doras-to/doras#44]
**Describe the bug**
When you navigate from home to story, the toolips for the badges break.

**To Reproduce**
How did you produce this error?

1. Go to https://doras.to/tommerty
2. See tooltip working
3. Click Story
4. Hover toolips and see they're broken, even when nav back to home

**Expected behavior**
Shouldn't happen lol

**Screenshots**

![Image](https://github.com/doras-to/doras/assets/86270372/da8169dd-c827-4191-a9eb-35f290588e86)

![Image](https://github.com/doras-to/doras/assets/86270372/00603509-6ebe-4ee4-a5ad-c0573584ae32)

**Additional context**
I've talked about this bug before but not noticed how I could replicate it, until now

**Comment by trent-gezel** [comment]
view transitions fucks it

**Comment by tommerty** [comment]
Resolved with move to NextJS
