### ISSUE TITLE
Formatting of Text when adding to UI

### ISSUE THREAD

**Issue by DieBraaiMeester** [doras-to/doras#56]
See below as the text doesn't look very appealing to the UI. 
![image](https://github.com/doras-to/doras/assets/99278346/1a174797-c1b8-4576-a246-39f79c3535a4)

**Comment by tommerty** [comment]
Strongly agree, will work on it shortly!

**Comment by tommerty** [comment]
Sorry, I completely forgot to close this, I resolved this the other day!
