### ISSUE TITLE
buttons  go to 404 

### ISSUE THREAD

**Issue by Noclasss** [doras-to/doras#61]
clicking on view profile and design go to 404 
![Screenshot 2023-12-05 124147](https://github.com/doras-to/doras/assets/152980879/f35ed5f1-e767-49ca-9de3-d3d711b6689f)

-   Browser [. chrome,]
-   Version 119.0.6045.200 (Official Build) (64-bit)

**Comment by tommerty** [comment]
Hey @Noclasss, am on my lunch but this was a quick 2 second fix! Deploying now, should be live shortly! Thanks for the report! ❤
