### ISSUE TITLE
Losing my profile everytime I click on analytics

### ISSUE THREAD

**Issue by Ibailzy** [doras-to/doras#67]
### Brief Overview

When I click on the analytics button in the 'Link' Item it reverts all progress made on profile 

### Expanded Description

When I click on the analytics button in the 'Link' Item it reverts all progress made on profile:
![image](https://github.com/doras-to/doras/assets/66921521/18b15e48-3a83-4217-a0e3-3479d7f67193)

### Which site is this issue on?

nua.doras.to

**Comment by tommerty** [comment]
Aye mate! I assume you're clicking the analytics before clicking "save changes"? Mind showing a screen recording when you get a chance? Just having trouble replicating!

**Comment by Ibailzy** [comment]
https://github.com/doras-to/doras/assets/66921521/c06bcceb-016b-460f-aa1c-94aceb9f8fe3

You don't see it on the video but I click the back button at top left to go back to the profile which is what then returns the profile to an older state.

**Comment by Ibailzy** [comment]
Google Chrome

**Comment by tommerty** [comment]
Interesting! In the nicest language possible, that's fucked 😅 We'll remove that button for the time being, it doesn't do anything that the other analytic buttons don't already do!

**Comment by tommerty** [comment]
Hey @Ibailzy, just pushed an update now to Nua to remove that button, we'll merge into main when we hit 0.0.14. 

If you continue to encounter this problem in any capacity in the future, please reopen the issue and let us know ❤
