### ISSUE TITLE
White text in Light mode

### ISSUE THREAD

**Issue by lady-d-22** [doras-to/doras#74]
### Brief Overview

White text on white background in Light mode

### Expanded Description

Selecting a colour in the colour wheel in light mode, the Hex code is white on a white background

<img width="230" alt="Screenshot 2023-12-13 at 13 00 55" src="https://github.com/doras-to/doras/assets/120519321/d59c7bff-f5de-4fa7-b35d-446fa9a504b2">

### Which site is this issue on?

admin.doras.to (Admin Dashboard)

### What browsers are you seeing the problem on (if applicable)?

Chrome

**Comment by tommerty** [comment]
darn light mode 

![Image](https://github.com/doras-to/doras/assets/86270372/5515d9f7-2695-4e83-8e92-5af26328eb47)

**Comment by tommerty** [comment]
Thanks for raising, will add it to my triage 😄

**Comment by tommerty** [comment]
Fix has been merged into staging and will be released with v0.0.14 😊 closing as a fix will be deployed
