### ISSUE TITLE
Girhub Statistics Card

### ISSUE THREAD

**Issue by DieBraaiMeester** [doras-to/doras#75]
### Brief Overview

Error showing File

### Expanded Description

When I clicked on the doras.to/braaimeesterza link and want to view the statistics the error pops up.

![image](https://github.com/doras-to/doras/assets/99278346/ab34a1a4-6f1a-4b36-a196-33528fbebb3d)

### Which site is this issue on?

nua.doras.to

### What browsers are you seeing the problem on (if applicable)?

Firefox

**Comment by tommerty** [comment]
Hey @DieBraaiMeester! 👋 

Yeah, seems to be a bug and it's only accepting URLs, but it should actually only accept the username. A fix will be deployed shortly 😊

**Comment by tommerty** [comment]
Hey @DieBraaiMeester,

@trent-gezel pushed and merged an update and this should now work on Nua and coming to main site in v0.0.14! Closing this for now, thanks again for your report ❤
