### ISSUE TITLE
Amazon/Throne Wishlist integration

### ISSUE THREAD

**Issue by DieBraaiMeester** [doras-to/doras#79]
### Tell us what you think!

I think it'd be cool if you could add somehow an Amazon or Thrones embedded wish list for the supporters

**Comment by tommerty** [comment]
Didn't know Throne had an embed! Will look into this! 😊

**Comment by tommerty** [comment]
Oh, they don't have a native embed thing, shoot. So when a website doesn't offer an embed, we'd literally need to try figure out a way to render the entire page in a frame and it gets super messy and unwieldy. Un less Throne or Amazon release this as a feature, there really is no way of handling this nicely :/ 

I can see people have requested this on Throne before, but it's been quiet for about a year. I just left a comment on it however: https://throne-gifts.upvoty.com/b/feature-requests/integrate-wishlist-into-website-blog/

So we literally just have to wait for them to add some sort of feature for people like us to be able to implement it!

I'm going to close this for now but if I hear back about it or if you see that they eventually allowed "embedding/iframe" please reopen and let me know! ❤
