### ISSUE TITLE
Media Kit Users

### ISSUE THREAD

**Issue by DieBraaiMeester** [doras-to/doras#86]
### Brief Overview

Users page not found

### Expanded Description

When I click on the media kit page, an users page not found - Sorry, we couldn't find what you were looking for. It either never existed, or we've messed something up! This shows even after saving all the information.

![image](https://github.com/doras-to/doras/assets/99278346/e5f2ab3a-9018-4ef1-b910-dda67fbfce6b)

### Which site is this issue on?

nua.doras.to

### What browsers are you seeing the problem on (if applicable)?

Firefox

**Comment by tommerty** [comment]
![Image](https://github.com/doras-to/doras/assets/86270372/3cb46613-31e2-4f87-bcb1-cb16ba9c42e0)


Click the toggle and it'll appear, that's just what shows up currently when mediakit isn't enabled

**Comment by DieBraaiMeester** [comment]
Ah found it as shown. 

Can there be an option to show enabled as this is very dark to see that it is off?

![image](https://github.com/doras-to/doras/assets/99278346/f121a432-a3a6-4388-af05-75e1b30e3427)

**Comment by tommerty** [comment]
@DieBraaiMeester absolutely, we'll be working on a feature in the future so that if you have any profiles added to mediakit it'll auto enable, and if there's no profiles attached it'll be automatically disabled. The placement of the toggle also isn't great, it'll be sorted before launch though :) Appreciate the alpha feedback ❤

**Comment by DieBraaiMeester** [comment]
Also to note that the stats didn't pull through at midnight gmt.

Mine noticed invalid date!

**Comment by tommerty** [comment]
@DieBraaiMeester that's interesting, thanks for letting us know. We'll take a look on the 26/27th if that's ok

**Comment by DieBraaiMeester** [comment]
Yes no problem at all.

**Comment by tommerty** [comment]
Hey @trent-gezel, just putting this on your radar. Looking at the array just seems everything is hitting `null` in terms of stats, so I imagine it's not fetching correctly? Looking at the usernames I can see it does look to be correct. I imagine something with the cron not hitting it?

**Comment by trent-gezel** [comment]
yeah looking into it

**Comment by trent-gezel** [comment]
@tommerty should be fixed

**Comment by DieBraaiMeester** [comment]
Thanks Tommy and Rent.

It's working now.

Will close this
