### ISSUE TITLE
Media Kit spacing on computer and mobile

### ISSUE THREAD

**Issue by DieBraaiMeester** [doras-to/doras#93]
Hey hey.

Not really a bug but more to feedback.

I noticed when viewing the mediakit on both computer browser and mobile browser the spacing is not very nice.

Attached is examples:

![image](https://github.com/doras-to/doras/assets/99278346/9b5334df-580f-481e-85b7-08461ae3a65a)
Above is when viewed from computer browser

![photo_2023-12-27_15-39-06](https://github.com/doras-to/doras/assets/99278346/68f77b80-508a-46ba-842d-879d91e8a24d)
Above from mobile device

**Comment by DieBraaiMeester** [comment]
I noticed the white block on the right but that is my bad snipping on windows. :P

**Comment by tommerty** [comment]
Hey @DieBraaiMeester, yeah it's ass if it's not displayed on desktop. I'll be working on improvements before the public release of mediakit (right now it's only available for Nua users) 😊 

I'll update this issue when I work on it :)

**Comment by DieBraaiMeester** [comment]
All good.

**Comment by tommerty** [comment]
@DieBraaiMeester a small fix is being deployed, let me know if that's any better! Also please, remove the red text you can't see your shit at all it looks hideous 😅

**Comment by DieBraaiMeester** [comment]
Red text with the main page?

**Comment by tommerty** [comment]
![Image](https://github.com/doras-to/doras/assets/86270372/68ec5b01-e6fb-424e-a558-eaf96fd57062)

The red text on your mediakit, it's very unreadable lol

**Comment by DieBraaiMeester** [comment]
Okay. I will fix it.

**Comment by DieBraaiMeester** [comment]
Better Tommy?

**Comment by tommerty** [comment]
Sorry for the delay! Much! Closing this out for now
