### ISSUE TITLE
Media Kit > Add Platforms

### ISSUE THREAD

**Issue by DieBraaiMeester** [doras-to/doras#99]
When at the Media Kit tab at Add platform when clicking the button nothing appear unless the following?

![image](https://github.com/doras-to/doras/assets/99278346/426988e0-c597-44c8-8bab-c789fd480f01)

Not sure if intended or still work in progress. :)

**Comment by tommerty** [comment]
Hey! Yeah so right now basically you can only have one of each platform, so when you click "add" and you've used all the slots, it's just currently blank!

I'll work on a better UI for that to indicate!

**Comment by DieBraaiMeester** [comment]
All good Tommy. That make sense. 😁
